#!/usr/bin/env python3
"""herdr-supervisor: fail-closed orchestration of existing Herdr Claude/Codex sessions.

The supervisor routes turns between two already-running native agent sessions.
It never decides workflow stages itself: the active agent reads the repository
instructions and declares the next stage in a machine-readable protocol block.

Design invariants (see docs/ARCHITECTURE.md):

* at-most-once task submission: delivery state is persisted before any prompt
  is sent, and a stalled/timed-out prompt is never replayed automatically;
* completion markers are accepted only when they match the current run id AND
  the current turn nonce, so stale terminal scrollback cannot route work;
* provider quota exhaustion waits in the same native session until the latest
  blocking window resets plus a buffer, then continues the same stage;
* `blocked` and `unknown` lifecycle states fail closed to WAIT_USER unless a
  provider quota screen is positively identified and the snapshot agrees;
* context usage is displayed but never used to replace a conversation;
* one worker per state directory, enforced with an OS file lock.
"""

from __future__ import annotations

# Compatibility facade and entry point. Every supported name keeps its identity: `import herdr_supervisor
# as hs` and the names companion modules and tests consume resolve to the single implementation in the
# owning module below. New code imports the owning module directly; nothing imports this facade back.
import dataclasses  # noqa: F401  (kept for callers that reach dataclasses/uuid through this module)
import uuid  # noqa: F401

from herdr_cli import (  # noqa: F401
    MIN_HERDR_VERSION,
    MIN_HERDR_VERSION_TEXT,
    OPTIONAL_CAPABILITIES,
    REQUIRED_CAPABILITIES,
    HerdrCli,
    IdentityMatch,
    command_error_code,
    evaluate_contract,
    match_exact_session,
    parse_herdr_version,
    session_identity,
)
from herdr_command import (  # noqa: F401
    _print_quota,
    build_parser,
    main,
    migrate_install,
    print_doctor,
    print_status,
    request_control,
    show_logs,
)
from herdr_core import (  # noqa: F401
    _LINE_PREFIX_RE,
    _STAGE_RE,
    _UUID_RE,
    ACTIONABLE_EVENTS,
    COMPLETION_MODES,
    DEFAULT_CONFIG,
    EVENT_NAMESPACE,
    EVENT_TYPES,
    FOLLOWUP_STATES,
    FOLLOWUP_UNRESOLVED,
    GATE_STATE_FOR,
    GATE_STATES,
    GATE_TYPES,
    HANDOFF_UNMET_KINDS,
    HUMAN_WAIT_STATES,
    LIFECYCLE_STATES,
    MAX_EPOCH,
    MAX_FOLLOWUP_QUESTION_CHARS,
    MAX_HANDOFF_NOTE_CHARS,
    PLAN_CHANGED_MESSAGE,
    PROTOCOL_KEYS,
    PROTOCOL_KEYS_V2,
    PROVIDERS,
    QUOTA_KINDS,
    READY_STATES,
    ROUTES,
    SCHEMA_VERSION,
    SHA_RE,
    STATE_SCHEMA_VERSION,
    SUPERVISOR_STATES,
    SUPERVISOR_VERSION,
    TERMINAL_STATES,
    WORKFLOW_POLICIES,
    HerdrError,
    Paths,
    QuotaError,
    SupervisorError,
    WorkerLock,
    _epoch,
    _number,
    atomic_write_json,
    canonical_json,
    deep_merge,
    iso_local,
    iso_utc,
    load_config,
    load_json,
    normalize_version,
    pid_alive,
    resolve_config_defaults,
    resolve_herdr_bin,
    sha256_bytes,
    sha256_file,
    xdg_state_home,
)
from herdr_protocol import (  # noqa: F401
    _DECORATION_ROW_RE,
    _FIELD_MAX_CHARS,
    _MACHINE_KEYS,
    _MAX_FRAME_ROWS,
    _MAX_LEGACY_HANDOFF_ROWS,
    FollowupFrame,
    ProtocolBlock,
    _continuation_fragment,
    _frame_prefix,
    _join_wrapped_text,
    _normalize_line,
    _parse_block,
    find_protocol_blocks,
    parse_followup,
    parse_protocol,
)
from herdr_quota import (  # noqa: F401
    QuotaSnapshot,
    QuotaWindow,
    _parse_windows,
    _select_windows,
    blocking_windows,
    parse_quota_snapshot,
    quota_as_dict,
    quota_resume_at,
)
from herdr_runtime import (  # noqa: F401
    MissingAgentError,
    Supervisor,
    backup_doctor_summary,
    telegram_doctor_summary,
)
from herdr_validation import (  # noqa: F401
    _MAX_METRIC,
    _SHA256_RE,
    _TASK_TEXT_CONTROL_RE,
    _UPLOAD_ID_RE,
    _UPLOAD_KEYS_OPTIONAL,
    _UPLOAD_KEYS_REQUIRED,
    UPLOAD_STATUSES,
    StateStore,
    _bool,
    _bounded_list,
    _bounded_str,
    _exact_str,
    _validate_completion,
    _validate_handoff_ready,
    _validate_missing_result,
    _validate_prompt_metrics,
    _validate_unmet,
    check_safe_file,
    git_head,
    load_query_registry,
    load_task_file,
    migrate_state_v1,
    new_v2_fields,
    query_owner_summary,
    register_query_provider,
    safe_gate_view,
    validate_gate_payload,
    validate_runtime_evidence,
    validate_state_v2,
    validate_task_text,
    validate_upload_record,
)
from herdr_workflow import (  # noqa: F401
    SupervisorV2Mixin,
)

__all__ = [
    "IdentityMatch",
    "match_exact_session",
    "MissingAgentError",
    "MIN_HERDR_VERSION",
    "MIN_HERDR_VERSION_TEXT",
    "REQUIRED_CAPABILITIES",
    "OPTIONAL_CAPABILITIES",
    "parse_herdr_version",
    "evaluate_contract",
    "SUPERVISOR_VERSION",
    "normalize_version",
    "ACTIONABLE_EVENTS",
    "COMPLETION_MODES",
    "DEFAULT_CONFIG",
    "EVENT_NAMESPACE",
    "EVENT_TYPES",
    "FOLLOWUP_STATES",
    "FOLLOWUP_UNRESOLVED",
    "FollowupFrame",
    "GATE_STATES",
    "GATE_STATE_FOR",
    "GATE_TYPES",
    "HANDOFF_UNMET_KINDS",
    "HUMAN_WAIT_STATES",
    "HerdrCli",
    "HerdrError",
    "LIFECYCLE_STATES",
    "MAX_EPOCH",
    "MAX_FOLLOWUP_QUESTION_CHARS",
    "MAX_HANDOFF_NOTE_CHARS",
    "PLAN_CHANGED_MESSAGE",
    "PROTOCOL_KEYS",
    "PROTOCOL_KEYS_V2",
    "PROVIDERS",
    "Paths",
    "ProtocolBlock",
    "QUOTA_KINDS",
    "QuotaError",
    "QuotaSnapshot",
    "QuotaWindow",
    "READY_STATES",
    "ROUTES",
    "SCHEMA_VERSION",
    "SHA_RE",
    "STATE_SCHEMA_VERSION",
    "SUPERVISOR_STATES",
    "StateStore",
    "Supervisor",
    "SupervisorError",
    "SupervisorV2Mixin",
    "TERMINAL_STATES",
    "UPLOAD_STATUSES",
    "WORKFLOW_POLICIES",
    "WorkerLock",
    "_DECORATION_ROW_RE",
    "_FIELD_MAX_CHARS",
    "_LINE_PREFIX_RE",
    "_MACHINE_KEYS",
    "_MAX_FRAME_ROWS",
    "_MAX_LEGACY_HANDOFF_ROWS",
    "_MAX_METRIC",
    "_SHA256_RE",
    "_STAGE_RE",
    "_TASK_TEXT_CONTROL_RE",
    "_UPLOAD_ID_RE",
    "_UPLOAD_KEYS_OPTIONAL",
    "_UPLOAD_KEYS_REQUIRED",
    "_UUID_RE",
    "_bool",
    "_bounded_list",
    "_bounded_str",
    "_continuation_fragment",
    "_epoch",
    "_exact_str",
    "_frame_prefix",
    "_join_wrapped_text",
    "_normalize_line",
    "_number",
    "_parse_block",
    "_parse_windows",
    "_print_quota",
    "_select_windows",
    "_validate_completion",
    "_validate_handoff_ready",
    "_validate_missing_result",
    "_validate_prompt_metrics",
    "_validate_unmet",
    "atomic_write_json",
    "backup_doctor_summary",
    "blocking_windows",
    "build_parser",
    "canonical_json",
    "check_safe_file",
    "command_error_code",
    "deep_merge",
    "find_protocol_blocks",
    "git_head",
    "iso_local",
    "iso_utc",
    "load_config",
    "load_json",
    "load_query_registry",
    "load_task_file",
    "main",
    "migrate_install",
    "migrate_state_v1",
    "new_v2_fields",
    "parse_followup",
    "parse_protocol",
    "parse_quota_snapshot",
    "pid_alive",
    "print_doctor",
    "print_status",
    "query_owner_summary",
    "quota_as_dict",
    "quota_resume_at",
    "register_query_provider",
    "request_control",
    "resolve_config_defaults",
    "resolve_herdr_bin",
    "safe_gate_view",
    "session_identity",
    "sha256_bytes",
    "sha256_file",
    "show_logs",
    "telegram_doctor_summary",
    "validate_gate_payload",
    "validate_runtime_evidence",
    "validate_state_v2",
    "validate_task_text",
    "validate_upload_record",
    "xdg_state_home",
]

if __name__ == "__main__":
    raise SystemExit(main())
